services:
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    ports:
      - 80:80
    env_file:
      - ./frontend/.env
    volumes:
      - webdata:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
      - ./frontend/nginx/conf/dev.conf:/etc/nginx/conf.d/default.conf

  certbot:
    image: certbot/certbot
    volumes:
      - webdata:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email ${CERTBOT_EMAIL} --no-eff-email --agree-tos -d ${CERTBOT_DOMAIN} --force-renewal
    depends_on:
      - frontend

volumes:
  webdata:
  letsencrypt: