services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - webdata:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
      - ./frontend/nginx/conf/cert.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chatbot-network

  certbot:
    image: certbot/certbot
    volumes:
      - webdata:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email ${CERTBOT_EMAIL} --no-eff-email --agree-tos -d ${CERTBOT_DOMAIN} --expand --force-renewal
    networks:
      - chatbot-network
    depends_on:
      - nginx

volumes:
  webdata:
  letsencrypt:
    
networks:
  chatbot-network:
    driver: bridge