#cloud-config
---
groups:
  - debian: [root, sys]
  - terraform

users:
  - default
  - name: ${user}
    gecos: terraform
    primary_group: terraform
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_key}
