name: Deploy to Infomaniak Cloud

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      env:
        OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
        OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
        OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      env:
        OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
        OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
        OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
        TF_VAR_name: "chatbot-instance"
        TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Save Terraform State
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: terraform/terraform.tfstate

    - name: Save Instance IP
      id: save_ip
      run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV
      working-directory: terraform

    - name: Add instance IP to inventory
      run: |
        echo "[app]" > ansible/inventory.ini
        echo "${{ env.INSTANCE_IP }} ansible_user=ubuntu" >> ansible/inventory.ini

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/playbook/deploy.yml
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        inventory: |
          [app]
          ${{ env.INSTANCE_IP }} ansible_user=ubuntu
        options: --extra-vars "openai_api_key=${{ secrets.OPENAI_API_KEY }} postgres_user=${{ secrets.POSTGRES_USER }} postgres_password=${{ secrets.POSTGRES_PASSWORD }} postgres_db=${{ secrets.POSTGRES_DB }} ngrok_auth_token=${{ secrets.NGROK_AUTH_TOKEN }} public_ip=${{ env.INSTANCE_IP }}"
